import { StyleSheet } from "react-native";

const tokens = {
  emerald100: "#d1fae5",
  emerald700: "#047857",
  neutral100: "#f5f5f5",
  neutral200: "#e5e5e5",
  neutral300: "#d4d4d4",
  neutral50: "#fafafa",
  neutral500: "#737373",
  neutral600: "#525252",
  neutral700: "#404040",
  neutral900: "#171717",
  red200: "#fecaca",
  red50: "#fef2f2",
  red700: "#b91c1c",
  white: "#ffffff",
};

const styles = StyleSheet.create({
  accountAddress: {
    color: tokens.neutral700,
    flex: 1,
    fontFamily: "Menlo",
    fontSize: 12,
  },
  accountAddressActive: {
    color: tokens.emerald700,
    flex: 1,
    fontFamily: "Menlo",
    fontSize: 12,
  },
  accountList: { flex: 1, gap: 4 },
  accountRow: {
    alignItems: "center",
    borderColor: tokens.neutral200,
    borderRadius: 6,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  accountRowActions: { alignItems: "center", flexDirection: "row", gap: 8 },
  accountRowCurrent: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
  },
  actionRow: { flexDirection: "row", gap: 8 },
  activeBadge: {
    backgroundColor: tokens.emerald100,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  activeBadgeText: {
    color: tokens.emerald700,
    fontSize: 12,
    fontWeight: "500",
  },
  activeCard: {
    backgroundColor: tokens.white,
    borderColor: tokens.neutral200,
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 20,
  },
  activeHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  activeIcon: { borderRadius: 4, height: 32, width: 32 },
  activeName: { color: tokens.neutral900, fontSize: 16, fontWeight: "600" },
  bodySmall: { color: tokens.neutral600, fontSize: 14, marginTop: 8 },
  brandPlatformList: { flexDirection: "row", gap: 8 },
  chainChip: {
    borderColor: tokens.neutral300,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  chainChipCurrent: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
  },
  chainChipText: { color: tokens.neutral700, fontSize: 12 },
  chainChipTextCurrent: {
    color: tokens.emerald700,
    fontSize: 12,
    fontWeight: "500",
  },
  chainList: { flex: 1, flexDirection: "row", flexWrap: "wrap", gap: 6 },
  container: {
    marginHorizontal: "auto",
    maxWidth: 672,
    paddingHorizontal: 24,
    paddingVertical: 40,
    width: "100%",
  },
  countPill: {
    backgroundColor: tokens.neutral100,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  countPillText: {
    color: tokens.neutral500,
    fontFamily: "Menlo",
    fontSize: 12,
  },
  dd: { color: tokens.neutral900, flex: 1, fontFamily: "Menlo", fontSize: 12 },
  dlRow: { flexDirection: "row" },
  dt: { color: tokens.neutral500, fontSize: 14, width: 112 },
  emptyCard: {
    backgroundColor: tokens.neutral50,
    borderColor: tokens.neutral200,
    borderRadius: 8,
    borderWidth: 1,
    padding: 24,
  },
  errorBox: {
    backgroundColor: tokens.red50,
    borderColor: tokens.red200,
    borderRadius: 6,
    borderWidth: 1,
    padding: 12,
  },
  errorText: { color: tokens.red700, fontSize: 14 },
  groupHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  groupHeading: { color: tokens.neutral700, fontSize: 14, fontWeight: "500" },
  h1: {
    color: tokens.neutral900,
    fontSize: 30,
    fontWeight: "700",
    letterSpacing: -0.5,
  },
  h2: { color: tokens.neutral900, fontSize: 16, fontWeight: "600" },
  header: { marginBottom: 32 },
  lede: { color: tokens.neutral500, fontSize: 14, marginTop: 4 },
  muted: { color: tokens.neutral500, fontSize: 12 },
  outlineButton: {
    alignSelf: "flex-start",
    borderColor: tokens.neutral300,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  outlineButtonText: { color: tokens.neutral700, fontSize: 14 },
  platformChip: {
    borderColor: tokens.neutral300,
    borderRadius: 6,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  platformChipText: {
    color: tokens.neutral700,
    fontFamily: "Menlo",
    fontSize: 12,
  },
  root: { backgroundColor: tokens.white, flex: 1 },
  signButton: {
    backgroundColor: tokens.white,
    borderColor: tokens.neutral300,
    borderRadius: 4,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  signButtonText: { color: tokens.neutral700, fontSize: 12 },
  signError: { color: tokens.red700, fontSize: 12 },
  signOk: { color: tokens.emerald700, fontSize: 12 },
  stack: { gap: 24 },
  stackSmall: { gap: 8 },
  statusLabel: { color: tokens.neutral600, fontSize: 14, fontWeight: "500" },
  statusPill: {
    backgroundColor: tokens.neutral100,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  statusPillText: {
    color: tokens.neutral600,
    fontFamily: "Menlo",
    fontSize: 12,
  },
  statusRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  titleRow: { alignItems: "center", flexDirection: "row", gap: 8 },
  walletIcon: { borderRadius: 4, height: 24, width: 24 },
  walletName: { color: tokens.neutral900, fontSize: 14, fontWeight: "500" },
  walletRow: {
    alignItems: "center",
    backgroundColor: tokens.white,
    borderColor: tokens.neutral200,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  walletRowLeft: { alignItems: "center", flexDirection: "row", gap: 12 },
});

export { styles, tokens };
