packages:
  - apps/*
  - packages/*

allowBuilds:
  bigint-buffer: false
  bufferutil: true
  esbuild: true
  fallow: true
  keccak: true
  msgpackr-extract: false
  protobufjs: false
  sharp: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - "@oxlint-tsgolint/darwin-arm64@7.0.2001"
  - "@oxlint-tsgolint/darwin-x64@7.0.2001"
  - "@oxlint-tsgolint/linux-arm64@7.0.2001"
  - "@oxlint-tsgolint/linux-x64@7.0.2001"
  - "@oxlint-tsgolint/win32-arm64@7.0.2001"
  - "@oxlint-tsgolint/win32-x64@7.0.2001"
  - oxlint-tsgolint@7.0.2001
  - oxlint-config-awesomeness@3.4.2
  - "@tanstack/react-router-devtools@1.167.1"
  - "@tanstack/react-router@1.170.19"
  - "@tanstack/react-start-client@1.168.17"
  - "@tanstack/react-start-rsc@0.1.35"
  - "@tanstack/react-start-server@1.167.24"
  - "@tanstack/react-start@1.168.36"
  - "@tanstack/router-core@1.171.16"
  - "@tanstack/router-devtools-core@1.168.1"
  - "@tanstack/router-generator@1.167.22"
  - "@tanstack/router-plugin@1.168.24"
  - "@tanstack/start-client-core@1.170.15"
  - "@tanstack/start-plugin-core@1.171.27"
  - "@tanstack/start-server-core@1.169.19"
  - "@tanstack/start-storage-context@1.167.18"
  - oxlint-plugin-react-doctor@0.9.6

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - bufferutil
  - esbuild
  - fallow
  - keccak
  - lightningcss
  - msw
  - prisma
  - sharp
  - unrs-resolver
  - utf-8-validate
