/**
 * Declared inline rather than taken from `viem`, which would expand butr's
 * footprint. Loose on purpose: `request(...)` returns `unknown` and the
 * `request*` helpers narrow it at the boundary.
 */

type Eip1193RequestArgs = {
  method: string;
  params?: ReadonlyArray<unknown> | object;
};

type Eip1193Listener = (...args: ReadonlyArray<unknown>) => void;

type Eip1193Provider = {
  on: (event: string, listener: Eip1193Listener) => void;
  removeListener: (event: string, listener: Eip1193Listener) => void;
  request: (args: Eip1193RequestArgs) => Promise<unknown>;
};

type Eip6963ProviderInfo = {
  /** Data URI or absolute URL pointing at the wallet's icon. */
  icon: string;
  /** Human-readable wallet name shown in pickers. */
  name: string;
  /** Reverse-DNS identifier: `io.metamask`, `io.rabby`, `app.phantom`.
   *  Stable across versions, unique per wallet, used as the pool key. */
  rdns: string;
  /** Per-page UUID generated by the wallet. Not stable across reloads. */
  uuid: string;
};

type Eip6963ProviderDetail = {
  info: Eip6963ProviderInfo;
  provider: Eip1193Provider;
};

type Eip6963AnnounceEvent = CustomEvent<Eip6963ProviderDetail>;

/** `provider.request` is typed `unknown` by design; these helpers narrow
 *  the well-known EVM RPC shapes at the boundary with runtime guards so
 *  call sites stay assertion-free. A malformed response is reported as
 *  `null` / `[]` rather than a blank value, so call sites that cannot
 *  proceed without a real one fail instead of inventing a default. */
const requestString = async (
  provider: Eip1193Provider,
  args: Eip1193RequestArgs,
): Promise<string | null> => {
  const result = await provider.request(args);
  return typeof result === "string" ? result : null;
};

const requestStringArray = async (
  provider: Eip1193Provider,
  args: Eip1193RequestArgs,
): Promise<Array<string>> => {
  const result = await provider.request(args);
  return Array.isArray(result)
    ? result.filter((item): item is string => typeof item === "string")
    : [];
};

export { requestString, requestStringArray };

export type {
  Eip1193Listener,
  Eip1193Provider,
  Eip1193RequestArgs,
  Eip6963AnnounceEvent,
  Eip6963ProviderDetail,
  Eip6963ProviderInfo,
};
