/**
 * Minimal EIP-1193 / EIP-6963 type surface — declared inline rather
 * than imported from `@types/ethereum` (which doesn't exist as a
 * cohesive package) or `viem` (which would expand butr's footprint).
 *
 * These types describe only the methods butr's auto-discovery layer
 * actually calls on a provider. They're intentionally loose
 * (`request(...)` returns `unknown`) so individual call sites can
 * narrow the result via a cast.
 */

type Eip1193RequestArgs = {
  method: string;
  params?: ReadonlyArray<unknown> | object;
};

type Eip1193Listener = (...args: ReadonlyArray<unknown>) => void;

type Eip1193Provider = {
  on(event: string, listener: Eip1193Listener): void;
  removeListener(event: string, listener: Eip1193Listener): void;
  request(args: Eip1193RequestArgs): Promise<unknown>;
};

type Eip6963ProviderInfo = {
  /** Data URI or absolute URL pointing at the wallet's icon. */
  icon: string;
  /** Human-readable wallet name shown in pickers. */
  name: string;
  /** Reverse-DNS identifier — `io.metamask`, `io.rabby`, `app.phantom`.
   *  Stable across versions, unique per wallet, used as the pool key. */
  rdns: string;
  /** Per-page UUID generated by the wallet. Not stable across reloads. */
  uuid: string;
};

type Eip6963ProviderDetail = {
  info: Eip6963ProviderInfo;
  provider: Eip1193Provider;
};

type Eip6963AnnounceEvent = CustomEvent<Eip6963ProviderDetail>;

export type {
  Eip1193Listener,
  Eip1193Provider,
  Eip1193RequestArgs,
  Eip6963AnnounceEvent,
  Eip6963ProviderDetail,
  Eip6963ProviderInfo,
};
